### ISSUE TITLE
Server error when opening some articles

### ISSUE THREAD

**Issue by nbabaka** [noticeable-app/noticeable#1] opened 2021-02-19 18:17 UTC
I've created some articles and add an image there. Users can see it in the timeline, but can not open the article to have details and a full description. The error is -
{"message":"Internal Server Error: Not Found","logref":null,"path":null,"_links":{},"_embedded":{}}

https://changelog.cinemood.com/
and try to open the first article.

**Comment by nbabaka** [comment] 2021-02-19 18:21
I see there is no information in the link.

**Comment by nbabaka** [comment] 2021-02-19 18:23
I got the bug - there is an empty slug thereafter I've added the image.

**Comment by laurentpellegrino** [comment] 2021-02-19 19:19
@nbabaka Thanks for creating this issue. 

I just tried creating a publication and attaching a featured image but I cannot reproduce what you experienced. 

Could you please share the steps to reproduce the problem? when you say that you added an image, are you speaking about the featured image of your publication?

**Comment by laurentpellegrino** [comment] 2021-02-22 21:31
@nbabaka We would need your help to know what are the steps to reproduce the problem. Without this information, we cannot progress and will have to close the issue after some days.

**Comment by laurentpellegrino** [comment] 2021-03-01 14:15
Closing as we can't reproduce. Do not hesitate to reopen or create a new issue if you have reproduction steps to share.

**Closed as completed by laurentpellegrino** 2021-03-01 14:15 UTC
Labels: question
